// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/erik1502/Cloud/web/templates/layouts"

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"m-5 border border-line rounded-md bg-white p-5\"><h2>Budget</h2><form id=\"budget-form\" class=\"flex flex-wrap gap-2\"><input type=\"text\" class=\"\" id=\"budget-name\" placeholder=\"Budget Name\" required> <input type=\"number\" id=\"budget-amount\" placeholder=\"Amount\" required> <button type=\"submit\" class=\"btn btn-success\">Add Budget</button></form><div class=\"expense-table my-4 relative overflow-x-auto\"><table class=\"w-full text-md text-left rtl-text-right\"><thead class=\"text-sm uppercase bg-gray-50 \"><tr><th scope=\"col\" class=\"px-6 py-3\">Budget Name</th><th scope=\"col\" class=\"px-6 py-3\">Amount</th></tr></thead> <tbody id=\"budget-list\"></tbody></table></div><div class=\"total-amount text-end\">Budget Total: $<span id=\"budget-total\">0.00</span></div><h2 class=\"mt\">Expenses</h2><form id=\"expense-form flex flex-wrap gap-2\"><input type=\"text\" id=\"expense-name\" placeholder=\"Expense Name\" required> <input type=\"number\" id=\"expense-amount\" placeholder=\"Amount\" required> <button type=\"submit\" class=\"btn btn-danger\">Add Expense</button></form><div class=\"expense-table\"><table class=\"w-full text-md text-left rtl-text-right\"><thead class=\"text-sm uppercase bg-gray-50 \"><tr><th scope=\"col\" class=\"px-6 py-3\">Expense Name</th><th scope=\"col\" class=\"px-6 py-3\">Amount</th></tr></thead> <tbody id=\"expense-list\"></tbody></table></div><div class=\"total-amount text-end\">Expenses Total: $<span id=\"expense-total\">0.00</span></div><h1>Balance</h1><div class=\"total-balance mt-5\">Balance Total: $<span id=\"balance-total\">0.00</span></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.PageLayout("Home").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
