// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SideBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside class=\"w-[300px] duration-300 overflow-hidden py-4 border-e border-line bg-white\" id=\"sidebar\"><div><div class=\"px-4 pb-2\"><img src=\"../../static/images/BRIANlysis.png\" width=\"157\" height=\"33\"></div><div class=\"horizontal-line\"></div><ul class=\"flex flex-col\"><li class=\"flex items-center my-2 px-4 py-2 gap-5 hover:text-primary cursor-pointer hover:bg-secondary rounded-md\"><i class=\"fa-solid fa-gauge-simple-high text-[32px]\"></i> <a href=\"/dashboard\" class=\"side-menu-list\">Dashboard</a></li><li class=\"flex items-center my-2 px-4 py-2 gap-5 hover:text-primary cursor-pointer hover:bg-secondary rounded-md\"><i class=\"fa-solid fa-list text-[32px]\"></i> <a href=\"/transactions\" class=\"side-menu-list\">Transactions</a></li><li class=\"flex items-center my-2 px-4 py-2 gap-5 hover:text-primary cursor-pointer hover:bg-secondary rounded-md active:text-primary\"><i class=\"fa-solid fa-coins text-[32px]\"></i> <a href=\"/budget_and_expense\" class=\"side-menu-list\">Budget and Expense</a></li><div class=\"horizontal-line\"></div><li class=\"flex items-center my-2 px-4 py-2 gap-5 hover:text-primary cursor-pointer hover:bg-secondary rounded-md\"><i class=\"fa-solid fa-download text-[32px]\"></i> <a href=\"/import\" class=\"side-menu-list\">Import/Export CSV file</a></li></ul></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
